### ISSUE TITLE
Spec tests

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#60]
When it comes time to write up SIMD spec tests, it will be useful to be aware of the tests that exist in other places.

Binaryen: https://github.com/WebAssembly/binaryen/blob/master/test/spec/simd.wast
Wabt: https://github.com/WebAssembly/wabt/tree/master/test/interp simd-*.txt

**Comment by AndrewScheidecker** [comment]
I also wrote some pretty limited tests for WAVM [here](https://github.com/WAVM/WAVM/blob/master/Test/simd.wast).

Trying the binaryen and wabt tests in WAVM I noticed a few incompatibilities:

* wabt implements SIMD compares to return 1 for true comparisons, but the proposed spec is to return -1 for true comparisons. Binaryen (and now WAVM) return -1 for true comparisons.
* Neither the Binaryen or wabt tests use the [proposed](https://github.com/WebAssembly/simd/blob/master/proposals/simd/TextSIMD.md) `v128.const` syntax.
* wabt has a `v8x16.shuffle` [test](https://github.com/WebAssembly/wabt/blob/master/test/interp/simd-lane.txt#L88) that uses a 4xi32 immediate. WAVM and Binaryen use a 16xi5 syntax.

**Comment by gnzlbg** [comment]
> wabt implements SIMD compares to return 1 for true comparisons, but the proposed spec is to return -1 for true comparisons. 

That's a bug, I've sent a PR that fixes that: https://github.com/WebAssembly/wabt/pull/1031

**Comment by tlively** [comment]
> * wabt has a `v8x16.shuffle` [test](https://github.com/WebAssembly/wabt/blob/master/test/interp/simd-lane.txt#L88) that uses a 4xi32 immediate. WAVM and Binaryen use a 16xi5 syntax.

I submitted #60 to standardize this.

**Comment by gnzlbg** [comment]
> wabt has a v8x16.shuffle test that uses a 4xi32 immediate. WAVM and Binaryen use a 16xi5 syntax.

I've implemented that (hopefully correctly) in WABT https://github.com/WebAssembly/wabt/pull/1032

**Comment by tlively** [comment]
@gnzlbg Thanks for your work on this! Are you planning to update WABT's v128.const syntax as well? No worries if not.

**Comment by gnzlbg** [comment]
> Are you planning to update WABT's v128.const syntax as well? 

I've updated the `v128.const i32` syntax to use `v128.const i32x4` syntax here: https://github.com/WebAssembly/wabt/pull/1033

But that PR does not implement any of the other constructors (e.g. `v128.const i64x2` errors).

**Comment by gnzlbg** [comment]
So the syntax part is fixed. I think this issue can be closed.

**Comment by tlively** [comment]
@gnzlbg this is a tracking issue for having spec tests, which we still don't have. We have a bunch of tests for different tools that can be used as a starting point for writing spec tests, though.

**Comment by Honry** [comment]
@tlively and all, 

I've been involved and improved the test coverage of WASM spec tests (My [PRs](https://github.com/WebAssembly/spec/issues?q=is%3Apr+author%3AHonry+is%3Aclosed)) and would like to contribute spec tests for SIMD as well. I've already made a rough plan with @arunetm internally, and now back to this thread to seek feedback from community.

**Test Design:** 
We will create WAST tests to align with the test design and test harness of the [WASM core spec tests](https://github.com/WebAssembly/spec/tree/master/test/core) to reduce efforts of upstreaming SIMD tests to WASM spec repo in future. Existing tests from various tools can be used as a starting point, including [WAVM](https://github.com/WAVM/WAVM/blob/master/Test/simd.wast), [WABT](https://github.com/WebAssembly/wabt/tree/master/test/interp), and [Binaryen](https://github.com/WebAssembly/binaryen/blob/master/test/spec/simd.wast).

**Test Framework:**
Before we have spec interpreter implementation for SIMD, I think WAVM is a good choice to be used as the test target since which has already supported all core proposal now and one more important point is that its [test framework](https://github.com/WAVM/WAVM/blob/master/Test/RunTestScript/RunTestScript.cpp) supports almost all the assertions of the WASM interpreter.

**Test Allocation:** 
How about creating a `test` folder under `/proposals/simd`?

**Test Validation:**
How to make sure tests pass on WAVM? Local validation or is that possible to integrate test framework from WAVM and enable it on CI for each test PR? The latter one seems not make sense as it's better to contribute tests to WAVM directly. thoughts?

This is really a rough plan and I may miss some other details. Please kindly provide your comments and suggestions, very appreciate!

**Comment by rossberg** [comment]
Is there a reason not to put the tests into test/core?

**Comment by Honry** [comment]
> Is there a reason not to put the tests into test/core?

@rossberg, yeah, it could be another option, I just missed it. So how about a new folder `test/core/simd`?

**Comment by binji** [comment]
For now, we've been putting tests for a proposal directly in the `test/core` directory in the proposals repository. It seems reasonable to do the same for SIMD.

**Comment by Honry** [comment]
@binji, thanks for the info! Let's use the `test/core` directly.

**Comment by tlively** [comment]
This sounds like a good plan. Thanks for taking on this work. As far as running the tests, I suggest writing the spec tests in a PR to the WAVM repo first, then copying them into this repo (in `test/core`, as suggested above). That way we will not need to set up any separate executable CI for this repo.

**Comment by Honry** [comment]
@tlively, @AndrewScheidecker and others, I've just submitted a PR for adding `v128.load` tests to WAVM(https://github.com/WAVM/WAVM/pull/159), please help review. Thanks!

**Comment by tlively** [comment]
Thanks for letting us know! Please continue posting updates to this thread, since I'm not subscribed to WAVM notficiations.

**Comment by ngzhian** [comment]
We have been adding a ton of tests to test/core/simd, I think this issue can be resolved.
